-- MySQL Script generated by MySQL Workbench
-- 03/02/17 15:49:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `BD_Biblioteca` ;

-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MAE_FACULTAD_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MAE_FACULTAD_BIB` (
  `id_fac` INT(4) NOT NULL AUTO_INCREMENT,
  `nombre_fac` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_fac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MAE_ADMINISTRACION_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MAE_ADMINISTRACION_BIB` (
  `id_adm` INT(4) NOT NULL AUTO_INCREMENT,
  `usuario_adm` VARCHAR(50) NOT NULL,
  `clave_adm` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_adm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MAE_CONFIGURACION_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MAE_CONFIGURACION_BIB` (
  `id_con` INT(4) NOT NULL AUTO_INCREMENT,
  `correo_con` VARCHAR(50) NOT NULL,
  `clave_con` VARCHAR(10) NOT NULL,
  `servidor_con` VARCHAR(20) NOT NULL,
  `puerto_con` VARCHAR(5) NOT NULL,
  `multa_con` DOUBLE NOT NULL,
  PRIMARY KEY (`id_con`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MAE_ESTUDIANTE_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MAE_ESTUDIANTE_BIB` (
  `id_est` INT(4) NOT NULL AUTO_INCREMENT,
  `cedula_est` VARCHAR(10) NOT NULL,
  `nombre_est` VARCHAR(50) NOT NULL,
  `telefono_est` VARCHAR(10) NOT NULL,
  `direccion_est` VARCHAR(50) NOT NULL,
  `semestre_est` VARCHAR(2) NOT NULL,
  `T_MAE_FACULTAD_BIB_id_fac` INT(4) NOT NULL,
  `mail_est` VARCHAR(50) NOT NULL,
  `clave_est` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_est`),
  INDEX `fk_T_MAE_ESTUDIANTE_BIB_T_MAE_FACULTAD_BIB_idx` (`T_MAE_FACULTAD_BIB_id_fac` ASC),
  CONSTRAINT `fk_T_MAE_ESTUDIANTE_BIB_T_MAE_FACULTAD_BIB`
    FOREIGN KEY (`T_MAE_FACULTAD_BIB_id_fac`)
    REFERENCES `BD_Biblioteca`.`T_MAE_FACULTAD_BIB` (`id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MAE_BIBLIOTECARIO_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MAE_BIBLIOTECARIO_BIB` (
  `id_bib` INT(4) NOT NULL AUTO_INCREMENT,
  `cedula_bib` VARCHAR(10) NOT NULL,
  `nombre_bib` VARCHAR(50) NOT NULL,
  `telefono_bib` VARCHAR(10) NOT NULL,
  `turno_bib` VARCHAR(30) NOT NULL,
  `mail_bib` VARCHAR(50) NOT NULL,
  `clave_bib` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_bib`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MAE_DOCUMENTO_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MAE_DOCUMENTO_BIB` (
  `id_doc` INT(4) NOT NULL AUTO_INCREMENT,
  `isbn_doc` VARCHAR(15) NOT NULL,
  `autor_doc` VARCHAR(50) NOT NULL,
  `editorial_doc` VARCHAR(30) NOT NULL,
  `titulo_doc` VARCHAR(50) NOT NULL,
  `area_doc` VARCHAR(50) NOT NULL,
  `anio_doc` INT(4) NOT NULL,
  `tipo_doc` VARCHAR(7) NOT NULL,
  `precio_doc` DOUBLE NOT NULL,
  `disponibilidad_doc` INT(2) NOT NULL,
  `reservados_doc` INT(2) NOT NULL,
  PRIMARY KEY (`id_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Biblioteca`.`T_MOV_RESERVA_BIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Biblioteca`.`T_MOV_RESERVA_BIB` (
  `id_res` INT(4) NOT NULL AUTO_INCREMENT,
  `T_MAE_ESTUDIANTE_BIB_id_est` INT(4) NOT NULL,
  `T_MAE_BIBLIOTECARIO_BIB_id_bib` INT(4) NOT NULL,
  `T_MAE_DOCUMENTO_BIB_id_doc` INT(4) NOT NULL,
  `titulodocumento_res` VARCHAR(50) NULL,
  `isbdocumento_res` VARCHAR(15) NULL,
  `preciodocumento_res` DOUBLE NULL,
  `fechareserva_res` DATETIME NULL, 
  `fechaprestamo_res` DATETIME NULL,
  `fechaentrega_res` DATETIME NULL,
  `fechadevolucion_res` DATETIME NULL,
  `subtotal_res` DOUBLE NULL,
  `total_res` DOUBLE NULL,
  `multa_res` DOUBLE NULL,
  PRIMARY KEY (`id_res`),
  INDEX `fk_T_MOV_RESERVA_BIB_T_MAE_ESTUDIANTE_BIB_idx` (`T_MAE_ESTUDIANTE_BIB_id_est` ASC),
  INDEX `fk_T_MOV_RESERVA_BIB_T_MAE_BIBLIOTECARIO_BIB_idx` (`T_MAE_BIBLIOTECARIO_BIB_id_bib` ASC),
  INDEX `fk_T_MOV_RESERVA_BIB_T_MAE_DOCUMENTO_BIB_idx` (`T_MAE_DOCUMENTO_BIB_id_doc` ASC),
  CONSTRAINT `fk_T_MOV_RESERVA_BIB_T_MAE_ESTUDIANTE_BIB`
    FOREIGN KEY (`T_MAE_ESTUDIANTE_BIB_id_est`)
    REFERENCES `BD_Biblioteca`.`T_MAE_ESTUDIANTE_BIB` (`id_est`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_MOV_RESERVA_BIB_T_MAE_BIBLIOTECARIO_BIB`
    FOREIGN KEY (`T_MAE_BIBLIOTECARIO_BIB_id_bib`)
    REFERENCES `BD_Biblioteca`.`T_MAE_BIBLIOTECARIO_BIB` (`id_bib`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_MOV_RESERVA_BIB_T_MAE_DOCUMENTO_BIB`
    FOREIGN KEY (`T_MAE_DOCUMENTO_BIB_id_doc`)
    REFERENCES `BD_Biblioteca`.`T_MAE_DOCUMENTO_BIB` (`id_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
